trigger:
- master

pr: none

schedules:
- cron: 0 */3 * * 1-5
  displayName: "Weekday Update"
  branches:
    include:
    - master
  always: true

jobs:
- job: build
  displayName: "Build site"
  pool:
    vmImage: "windows-2019"
  steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core 2.2.x"
    inputs:
      version: 2.2.x
  - task: DotNetCoreCLI@2
    displayName: "Install FAKE"
    inputs:
      command: custom
      custom: tool
      arguments: install fake-cli --tool-path .fake
  - script: .\.fake\fake.exe build -t generate
    displayName: "FAKE Generate"
  - publish: $(Build.SourcesDirectory)/public
    artifact: public

- deployment: netlify
  displayName: "Netlify Deploy"
  pool:
    vmImage: "ubuntu-16.04"
  environment: netlify-prod
  dependsOn: [ build ]
  strategy:
    runOnce:
      deploy:
        steps:
        - task: Npm@1
          inputs:
            command: custom
            customCommand: install netlify-cli
        - download: current
          artifact: public
        - script: npx netlify deploy --prod --dir $(Pipeline.Workspace)/public
          env:
            NETLIFY_AUTH_TOKEN: $(Netlify.Token)
            NETLIFY_SITE_ID: $(Netlify.SiteId)
