# releases-index-url = "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json"
releases-index-url = "https://github.com/arthurrump/dotnet-core/blob/github-url/release-notes/releases-index.json"

title = "Versions of .NET"
description = "versionsof.net gives an overview of all releases and versions of .NET Core."